steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gpt-researcher', '-f', 'Dockerfile.fullstack', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gpt-researcher']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gpt-researcher'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gpt-researcher'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '0'
      - '--port'
      - '3000'

images:
  - 'gcr.io/$PROJECT_ID/gpt-researcher'

options:
  logging: CLOUD_LOGGING_ONLY