steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gpt-researcher:$COMMIT_SHA', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gpt-researcher:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'gpt-researcher'
    - '--image'
    - 'gcr.io/$PROJECT_ID/gpt-researcher:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
images:
- 'gcr.io/$PROJECT_ID/gpt-researcher:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
