import { test, expect } from '@playwright/test';
import { takeScreenshot } from '../../fixtures/setup';
import { API_BASE } from '../../fixtures/queries';

test.describe('API - Reports CRUD', () => {
  const researchId = `e2e-test-${Date.now()}`;

  test.afterAll(async ({ request }) => {
    try {
      await request.delete(`${API_BASE}/api/reports/${researchId}`);
    } catch {
      // cleanup is best-effort
    }
  });

  test('create, read, update, delete report via API', async ({ page, request }, testInfo) => {
    const reportData = {
      id: researchId,
      question: 'E2E Test Query',
      answer: '# Test Report\n\nThis is a test report generated by E2E tests.',
    };

    await test.step('Create report', async () => {
      const createResp = await request.post(`${API_BASE}/api/reports`, {
        data: reportData,
      });
      expect(createResp.ok()).toBe(true);
      const body = await createResp.json();
      expect(body.success).toBe(true);
      expect(body.id).toBe(researchId);
      if (testInfo.project.name === 'api') {
        await takeScreenshot(page, testInfo, '01-report-created');
      }
    });

    await test.step('Read report by ID', async () => {
      const readResp = await request.get(`${API_BASE}/api/reports/${researchId}`);
      expect(readResp.ok()).toBe(true);
      const body = await readResp.json();
      expect(body.report.question).toBe('E2E Test Query');
    });

    await test.step('Read report list', async () => {
      const listResp = await request.get(`${API_BASE}/api/reports`);
      expect(listResp.ok()).toBe(true);
      const body = await listResp.json();
      expect(body.reports).toBeDefined();
      const found = body.reports.find((r: any) => r.id === researchId);
      expect(found).toBeDefined();
    });

    await test.step('Update report', async () => {
      const updateResp = await request.put(`${API_BASE}/api/reports/${researchId}`, {
        data: { answer: '# Updated Report Content' },
      });
      expect(updateResp.ok()).toBe(true);
    });

    await test.step('Delete report', async () => {
      const delResp = await request.delete(`${API_BASE}/api/reports/${researchId}`);
      expect(delResp.ok()).toBe(true);
    });

    await test.step('Verify deletion', async () => {
      const readResp = await request.get(`${API_BASE}/api/reports/${researchId}`);
      expect(readResp.status()).toBe(404);
      if (testInfo.project.name === 'api') {
        await takeScreenshot(page, testInfo, '02-report-deleted');
      }
    });
  });
});
