version: '3'

services:
  researcher-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: researcher-mcp-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped 