FROM node:18.17.0-alpine
WORKDIR /app
COPY ./package.json ./
RUN npm config set fetch-retries 5 \
    && npm config set fetch-retry-mintimeout 20000 \
    && npm config set fetch-retry-maxtimeout 120000 \
    && npm config set fetch-timeout 600000 \
    && npm install --legacy-peer-deps --no-audit --no-fund
COPY . .
CMD ["npm", "run", "dev"]
