name: GitHub Actions Workflow
run-name: ${{ github.actor }} has started docker build workflow.
on:
  pull_request:
    types: [opened, edited, ready_for_review]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build Dockerfile
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: assafelovic/gpt-researcher:latest
          file: Dockerfile

